apiVersion: v1
kind: Namespace
metadata:
  name: api-ns

---

kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: api-ns
spec:
  type: NodePort
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9001
  selector:
    app: api

---

# API configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: api-ns
data:
  api.hcl: |
    host = "0.0.0.0"
    port = 9001
    # host format: {service}.{ns}
    db_host = "customer-db.postgres-ns"
    db_port = 5432
    db_user = "symuser"
    db_name = "demodb"
    agent_sock = "unix:///run/spire/sockets/agent.sock"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api-ns
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: api
        spire.spiffe.io/spiffeid: db-access
    spec:
      containers:
        # API container
        - name: api
          image: api-service:latest-local
          imagePullPolicy: IfNotPresent
          args: ["-config", "/run/api/config/api.hcl"]
          volumeMounts:
            # Mount api config files
            - name: api-config
              mountPath: /run/api/config
              readOnly: true
            # Mount SPIRE-Agent socket
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: api-config
          configMap:
            name: api-config
        - name: spiffe-helper-config
          configMap:
            name: spiffe-helper-config
        - name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true

